### ISSUE TITLE
The question about the paper.

### ISSUE THREAD

**Issue by marsggbo** [arberzela/EfficientNAS#1]
Thank you very much for your work. And I have a question about the paper. In figure 1, what's the meaning of the wall clock time and why all types of budget reach to the same time point?

**Comment by arberzela** [comment]
Hey @marsggbo,

Thank you for the interest in our work. The wallclock time is just the relative time of each evaluation with respect to the BOHB start time, i.e.  configuration_evaluation_end_time - BOHB_start_time

There are configurations evaluated on smaller budgets also sampled in the end of the optimization, that is why some of them (seem to) end at the same point. The fact that the x-axis is in log scale also squashes more these points and makes them look closer to each other.

Hope this helps :)
Best,
Arber
